model:
  name: two_view_pipeline
  extractor:
    name: extractors.jpldd.joint_point_line_extractor
    training:
      do: False
    max_num_keypoints: 512
    line_detection:
      merge: True
    #checkpoint: rk_jpldd_11/checkpoint_best.tar
  matcher:
    name: matchers.line_matcher
benchmarks:
  megadepth1500:
    data:
    preprocessing:
      side: long
      resize: 1600
    eval:
      estimator: opencv
      ransac_th: 1.0
  hpatches:
    eval:
      estimator: opencv
      ransac_th: 0.5
    model:
      extractor:
        max_num_keypoints: 512 # overwrite config above
    use_points: False
    use_lines: True
