model:
  name: two_view_pipeline
  extractor:
    name: extractors.jpldd.joint_point_line_extractor
    #detector: pycolmap_cuda
    max_num_keypoints: 2048
    detection_threshold: 0.0
    nms_radius: 3
benchmarks:
  megadepth1500:
    data:
    preprocessing:
      side: long
      resize: 1600
    eval:
      estimator: opencv
      ransac_th: 1.0
  hpatches_lines:
    eval:
      estimator: opencv
      ransac_th: 0.5
    model:
      extractor:
        max_num_keypoints: 1024 # overwrite config above
  # hpatches:
  #   eval:
  #     estimator: opencv
  #     ransac_th: 0.5
  #   model:
  #     extractor:
  #       max_num_keypoints: 1024 # overwrite config above
  # eth3d:
  #   ground_truth:
  #     name: gluefactory.models.matchers.depth_matcher
  #     use_lines: True
  #   eval:
  #     plot_methods: [] # ['sp+NN', 'sp+sg', 'superpoint+lsd+gluestick']
  #     plot_line_methods: [] # ['superpoint+lsd+gluestick', 'sp+deeplsd+gs']