data:
    name: gluefactory.datasets.minidepth
    data_dir: "minidepth/images"  # as subdirectory of DATA_PATH(defined in settings.py)
    grayscale: False
    num_workers: 2  # defines processes used in Dataloader
    train_batch_size: 2
    val_batch_size: 2
    device: null
    prefetch_factor: 2
    preprocessing:
        resize: [ 800, 800 ]
    load_features:
        do: True
        check_exists: True
        check_nan: False
        device: null  # choose device to move groundtruthdata to if None is given, just read, skip move to device
        point_gt:
            path: "outputs/results/superpoint_gt"   # as subdirectory of DATA_PATH(defined in settings.py)
            data_keys: [ "superpoint_heatmap" ]
        line_gt:
            path: "outputs/results/deeplsd_gt"   # as subdirectory of DATA_PATH(defined in settings.py)
            data_keys: [ "deeplsd_distance_field", "deeplsd_angle_field" ]
model:
    name: jpldd.joint_point_line_extractor
    model_name: "aliked-n16"
    max_num_keypoints: 1000  # setting for training, for eval: -1
    pretrained: True
    timeit: True  # override timeit: False from BaseModel
    train_descriptors:
        do: False  # if train is True, initialize ALIKED Light model form OTF Descriptor GT
        device: null # device to house the lightweight ALIKED model
train:
    seed: 0
    epochs: 200
    log_every_iter: 1
    eval_every_iter: 700
    save_every_iter: 1400
    test_every_epoch: -1 # check if test deactivated
    optimizer: "adam"
    best_key: "loss/total"
    lr: 1e-4
    #lr_schedule:
    #    type: exp  # exp or multi_step
    #    start: 200e3
    #    exp_div_10: 200e3
    #    gamma: 0.5
    #    step: 50e3
    #    n_steps: 4
    submodules: []
    # clip_grad: 10  # Use only with mixed precision
    #load_experiment: jpldd_1