data:
    name: gluefactory.datasets.minidepth
    data_dir: "minidepth/images"  # as subdirectory of DATA_PATH(defined in settings.py)
    grayscale: False
    num_workers: 0  # defines processes used in Dataloader
    train_batch_size: 1  # 2 per GPU
    val_batch_size: 1
    device: null
    prefetch_factor: null
    preprocessing:
        resize: [ 800, 800 ]
    load_features:
        do: True
        check_exists: True
        check_nan: False
        device: null  # choose device to move ground_truthdata to if None is given, just read, skip move to device
        point_gt:
            path: "outputs/results/superpoint_gt"   # as subdirectory of DATA_PATH(defined in settings.py)
            data_keys: [ "superpoint_heatmap" ]
        line_gt:
            path: "outputs/results/deeplsd_gt"   # as subdirectory of DATA_PATH(defined in settings.py)
            data_keys: [ "deeplsd_distance_field", "deeplsd_angle_field" ]
model:
    name: jpldd.joint_point_line_extractor
    model_name: "aliked-n16"
    line_neighborhood: 5
    max_num_keypoints: 1000  # setting for training, for eval: -1
    training:
        do: True
        aliked_pretrained: True
        train_descriptors: True  # if train is True, initialize ALIKED Light model form OTF Descriptor GT
        pretrain_kp_decoder: False
        lambda_weighted_bce: 200
        loss_weights:
            line_af_weight: 10
            line_df_weight: 10
            keypoint_weight: 1
            descriptor_loss: 1
    checkpoint: null  # if given load model weights from this checkpoint
    timeit: True  # override timeit: False from BaseModel
train:
    load_experiment: null  # initialize the model from a previous experiment (take weights)
    seed: 0
    epochs: 100
    log_every_iter: 1
    eval_every_iter: 3000 # automatically creates new checkpoint if new best eval metric is reached -> set > batch size to not eval except at the end of each epoch
    save_every_iter: 500
    test_every_epoch: 10 # check if test deactivated
    optimizer: "adam"
    best_key: "loss/total" # key used to determine best checkpoint and evaluation progress
    lr: 0.001
    #lr_schedule:
    #    type: exp  # exp or multi_step
    #    start: 200e3
    #    exp_div_10: 200e3
    #    gamma: 0.5
    #    step: 50e3
    #    n_steps: 4
    submodules: []
    timeit: True    # print jpldd model mean timings every epoch
    # clip_grad: 10  # Use only with mixed precision
    #load_experiment: jpldd_1