model:
    name: two_view_pipeline
    extractor:
        name: #TODO
    matcher:
        name: matchers.line_matcher
benchmarks:
    megadepth1500:
        data:
            preprocessing:
            side: long
            resize: 1600
        eval:
            estimator: opencv
            ransac_th: 0.5
    hpatches:
        eval:
            estimator: opencv
            ransac_th: 0.5
        model:
            extractor:
                max_num_keypoints: 1024  # overwrite config above
